# common
.main-master: &main-master "master@development/common/abitech.nextapi"
.dotnet-job: &dotnet-job
  image: hub.abitech.kz/microsoft/dotnet:latest
  tags:
    - docker

.docker-job: &docker-job
  image: hub.abitech.kz/docker:latest
  tags:
    - docker

.docker: &docker
  tags:
    - docker

.dotnet-restore: &dotnet-restore "dotnet restore -v q --configfile ../../NuGet.config"

.dotnet-test: &dotnet-test
  stage: test
  <<: *dotnet-job
  only:
    - merge_requests
  script:
    - cd $project
    - *dotnet-restore
    - dotnet test -v d

.nugetize: &nugetize
  stage: build
  when: manual
  only:
    - *main-master
  <<: *dotnet-job
  script:
    - cd $projectFolder
    - dotnet pack -p:Version=$VERSION
    - dotnet nuget push "bin/Debug/$projectName.$VERSION.nupkg" -k $NugetApiKey  -s $NugetSource

# declaration
variables:
  VERSION: "1.8.0.$CI_PIPELINE_IID"

stages:
  - test
  - build

# tests
test-server:
  <<: *dotnet-test
  variables:
    project: test/Abitech.NextApi.Server.Tests
test-server-efcore:
  <<: *dotnet-test
  variables:
    project: test/Abitech.NextApi.Server.EfCore.Tests
test-client-di:
  <<: *dotnet-test
  variables:
    project: test/Abitech.NextApi.Client.Tests

# build/nugetize
nugetize-client:
  <<: *nugetize
  variables:
    projectFolder: src/client/Abitech.NextApi.Client
    projectName: Abitech.NextApi.Client
nugetize-client-autofac:
  <<: *nugetize
  variables:
    projectFolder: src/client/Abitech.NextApi.Client.Autofac
    projectName: Abitech.NextApi.Client.Autofac
nugetize-client-microsoft-di:
  <<: *nugetize
  variables:
    projectFolder: src/client/Abitech.NextApi.Client.MicrosoftDI
    projectName: Abitech.NextApi.Client.MicrosoftDI
nugetize-server:
  <<: *nugetize
  variables:
    projectFolder: src/Abitech.NextApi.Server
    projectName: Abitech.NextApi.Server
nugetize-server-efcore:
  <<: *nugetize
  variables:
    projectFolder: src/Abitech.NextApi.Server.EfCore
    projectName: Abitech.NextApi.Server.EfCore
