.dotnet-job: &dotnet-job
  image: hub.abitech.kz/microsoft/dotnet:latest
  tags:
    - docker

.docker-job: &docker-job
  image: hub.abitech.kz/docker:latest
  tags:
    - docker

.docker: &docker
  tags:
    - docker

.dotnet-restore: &dotnet-restore dotnet restore -v q --configfile ../../NuGet.config
.dotnet-release: &dotnet-release dotnet publish -c Release

.main-master: &main-master master@development/common/Abitech.NextApi

variables:
  VERSION: "1.0.0.$CI_PIPELINE_ID"

stages:
  - test
  - nugetize
  
test:
  <<: *dotnet-job
  stage: test
  script:
     - cd test/Abitech.NextApi.Server.Tests
     - *dotnet-restore
     - dotnet test -v n
nugetize: 
  <<: *dotnet-job
  # only:
    #  - *main-master
  stage: nugetize
  script:
     - sed -i "s/<Version>1.0.0<\/Version>/<Version>$VERSION<\/Version>/g" src/Abitech.NextApi.Server/Abitech.NextApi.Server.csproj
     - sed -i "s/<Version>1.0.0<\/Version>/<Version>$VERSION<\/Version>/g" src/Abitech.NextApi.Client/Abitech.NextApi.Client.csproj
     - cd src/Abitech.NextApi.Client
     - dotnet pack
     - dotnet dotnet nuget push "bin/Debug/Abitech.NextApi.Client.$VERSION.nupkg" -k $NugetApiKey  -s $NugetSource
     - cd ../src/Abitech.NextApi.Server
     - dotnet pack
     - dotnet dotnet nuget push "bin/Debug/Abitech.NextApi.Server.$VERSION.nupkg" -k $NugetApiKey  -s $NugetSource
