name: Common tests

on: 
  pull_request:
    branches: [ master ]

jobs:
  common-tests:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      projDir: [test/NextApi.Client.Tests, test/NextApi.Server.EfCore.Tests]
    container: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
    steps:
    - uses: actions/checkout@v2
    - name: Restoring packages...
      working-directory: ${{ matrix.projDir }}
      run: dotnet restore -v m
    - name: Building project...
      working-directory: ${{ matrix.projDir }}
      run: dotnet build -c Debug -v q --no-restore
    - name: Testing...
      working-directory: ${{ matrix.projDir }}
      run: dotnet test -v n --no-restore --no-build
